In [108]:
# 代码自动完成提示 tab 键
%config IPCompleter.greedy=True

# 一个 cell 可以多行输出
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all" 

In [ ]:
# vector, 向量，列向量，即使是矩阵的行，也是显示成列向量；
# matrix 按行，按列，对角阵，单位阵，全是 1 的矩阵；

# vector 内积 inner product, dot product，得一个数 scalar
# vector * vector

# 列的线性组合
# matrix * vector 
# matrix * matrix

# vector 和 vector 的外积, 也即：一个列向量，张成矩阵

# 向量投影

# 解 n 元一次方程，方阵求逆

# 特征值，特征向量
# SVD 分解

# QR 分解


In [34]:
import numpy as np
from scipy import linalg, sparse

In [2]:
# 列向量
v = np.array([1,2,3])

In [5]:
# 对应位置相乘，还是 vector
v * v

array([1, 4, 9])

In [6]:
# 向量内积运算，
np.dot(v,v)

14

In [7]:
# 手工模拟内积运算
sum(v * v)

14

In [9]:
# 矩阵, 按行
M = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
# 列的线性组合
np.dot(M, v)

array([14, 32, 50])

In [21]:
# 因为是按行创建，但是我们希望是指定列向量，所以在 transpose 一下
N = np.array([[1,1,0], [0,1,1], [0,0,1]])
N = N.T

N

array([[1, 0, 0],
       [1, 1, 0],
       [0, 1, 1]])

In [22]:
# 列的线性组合
np.dot(M, N)

array([[ 3,  5,  3],
       [ 9, 11,  6],
       [15, 17,  9]])

In [23]:
# 也是列的线性组合
M @ N

array([[ 3,  5,  3],
       [ 9, 11,  6],
       [15, 17,  9]])

In [32]:
# 由一个向量，张成一个矩阵

# 向量转成矩阵后，默认是 1*n
v_matrix = np.asmatrix(v)
v_matrix

matrix([[1, 2, 3]])

In [33]:
v_matrix.shape

(1, 3)

In [29]:
# 张成方阵：列向量 * 行向量
v_matrix.T @ v_matrix

matrix([[1, 2, 3],
        [2, 4, 6],
        [3, 6, 9]])

In [74]:
# 特征值，特征向量
A = np.array([[0,2,3], [-3, 2,1], [-2,1,3]]).T

A

array([[ 0, -3, -2],
       [ 2,  2,  1],
       [ 3,  1,  3]])

In [75]:
eigVals, eigVects = linalg.eig(A)

In [76]:
eigVals

array([1.78554932+2.95111266j, 1.78554932-2.95111266j,
       1.42890136+0.j        ])

In [77]:
# 这里显示还是按照行向量显示，但是列向量才是特征向量
eigVects

array([[-0.69374688+0.j        , -0.69374688-0.j        ,
        -0.30568793+0.j        ],
       [ 0.19624857+0.34577512j,  0.19624857-0.34577512j,
        -0.42305559+0.j        ],
       [ 0.32498679+0.50499992j,  0.32498679-0.50499992j,
         0.85298233+0.j        ]])

In [96]:
# 第一个特征向量
eigVects[:, 0]

array([-0.69374688+0.j        ,  0.19624857+0.34577512j,
        0.32498679+0.50499992j])

In [78]:
# SVD
B = np.array([[0,2,3], [-3, 2,1]]).T

B

array([[ 0, -3],
       [ 2,  2],
       [ 3,  1]])

In [140]:
# 返回值是 vt，不是 v
# s 是 vector，而不是对角阵
u, s, vt = linalg.svd(B)

u
s
vt

# 和手工计算结果比对用
s * s

array([[ 0.48471372,  0.80296442, -0.34684399],
       [-0.62402665,  0.03960025, -0.78039897],
       [-0.6128975 ,  0.59470998,  0.52026598]])

array([4.52966162, 2.54600974])

array([[-0.68145174, -0.73186305],
       [ 0.73186305, -0.68145174]])

array([20.51783442,  6.48216558])

In [144]:
# 手工计算 svd
C = B.T @ B
C

# 第二种写法
np.dot(B.T, B)

eigVals, eigVects = linalg.eig(C)

# 是 svd 返回的 s 的平方，但是没有按大小排列
eigVals

# 和 svd 中返回的 vt 一致，注意：
# 1. svd 是按照特征值从大到小返回，但是 eig 返回的不是，所以顺序不同；
# 2. 向量各分量值差一个负号，其实是一样的；
eigVects.T

array([[13,  7],
       [ 7, 14]])

array([[13,  7],
       [ 7, 14]])

array([ 6.48216558+0.j, 20.51783442+0.j])

array([[-0.73186305,  0.68145174],
       [-0.68145174, -0.73186305]])

In [153]:
# 由于 eigValus 不是从大到小排序，这里排一下序
# 从大到小排序，返回的 index的 array，但是可以直接当下标用
eigVals

idx = np.argsort(eigVals)[::-1]

# 和 svd 的结果，顺序就一致了
eigVals[idx]
eigVects[:, idx]

array([ 6.48216558+0.j, 20.51783442+0.j])

array([20.51783442+0.j,  6.48216558+0.j])

array([[-0.68145174, -0.73186305],
       [-0.73186305,  0.68145174]])

In [100]:
# 还原回去
# 由于 s 是 vector，需要变成 3 * 2 的矩阵，先做对角阵，然后再增加全零行
s_matrix = np.diag(s)

s_matrix = np.vstack([s_matrix, np.array([0, 0])])
s_matrix

array([[4.52966162, 0.        ],
       [0.        , 2.54600974],
       [0.        , 0.        ]])

In [102]:
# 矩阵乘法
u @ s_matrix @ vt

array([[-3.87898743e-17, -3.00000000e+00],
       [ 2.00000000e+00,  2.00000000e+00],
       [ 3.00000000e+00,  1.00000000e+00]])

In [109]:
v = vt.T

v

# 这是第一行，而不是第一列
v[0]

# 第一列
v[:, 0]

array([[-0.68145174,  0.73186305],
       [-0.73186305, -0.68145174]])

array([-0.68145174,  0.73186305])

array([-0.68145174, -0.73186305])

In [121]:
# 把多维数组，转成矩阵，  ndarray --> matrix
v_matrix = np.asmatrix(v)
v_matrix

# 矩阵求逆
linalg.inv(v_matrix)

matrix([[-0.68145174,  0.73186305],
        [-0.73186305, -0.68145174]])

array([[-0.68145174, -0.73186305],
       [ 0.73186305, -0.68145174]])

In [124]:
# 方程组求解
linalg.solve(v_matrix, np.array([1,2]))

array([-2.14517784, -0.63104043])

In [135]:
v1 = v[:, 0]
v2 = v[:, 1]

# 正交 内积
np.dot(v1, v2)
# 也是 内积
np.inner(v1, v2)

# 模长 1
np.inner(v1, v1)

# 向量张开 
v1
np.outer(v1, v1)

-0.68145174 * -0.68145174
-0.68145174 * -0.73186305

0.0

0.0

1.0

array([-0.68145174, -0.73186305])

array([[0.46437648, 0.49872935],
       [0.49872935, 0.53562352]])

0.46437647394902754

0.49872934886420695

In [162]:
B

q, r = linalg.qr(B)

q

# q 的列向量，正交，且单位化
np.dot(q[:, 0], q[:, 1])
np.dot(q[:, 2], q[:, 1])
np.dot(q[:, 2], q[:, 0])

np.dot(q[:, 0], q[:, 0])


# r 的列向量，是 q 列向量的线性组合，结果是 B 的一个列，也即：B 的一列，在 q 下的坐标
r

array([[ 0, -3],
       [ 2,  2],
       [ 3,  1]])

array([[ 0.        ,  0.93792284, -0.34684399],
       [-0.5547002 , -0.28859164, -0.78039897],
       [-0.83205029,  0.19239443,  0.52026598]])

-1.942890293094024e-16

6.938893903907228e-17

-5.551115123125783e-17

1.0

array([[-3.60555128, -1.94145069],
       [ 0.        , -3.19855737],
       [ 0.        ,  0.        ]])

In [169]:
a = np.array([2,4,3,1])
# 从小到大排序
np.sort(a)
np.argsort(a)


# 从大到小排序
np.sort(a)[::-1]
np.argsort(a)[::-1]

array([1, 2, 3, 4])

array([3, 0, 2, 1])

array([4, 3, 2, 1])

array([1, 2, 0, 3])