In [1]:
import numpy as np


In [3]:

a = np.array([1,2,3,4,5,6,7,8,9])
a

In [4]:
b = a.reshape(3,-1)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
c = a.reshape(-1,3)
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
type(a)

numpy.ndarray

In [8]:
# C: by row(last index change fast);  F: by column
d = a.reshape(3,-1, order="F")
d

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [10]:
e = np.reshape(a, (3,-1), order="C")
e

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
# [] 是 list； () 是 tuple

a = np.array([1,2,3])
b = np.array((4,5,6))


In [16]:
# 按 row 组成 matrix
c = np.stack((a,b))
c

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
# axis = -1 ==> 按 col 组成 matrix
d = np.stack((a, b), axis=-1)
d

array([[1, 4],
       [2, 5],
       [3, 6]])

In [20]:
x = np.ones((1, 2, 3))
x

array([[[1., 1., 1.],
        [1., 1., 1.]]])

In [21]:
y = np.transpose(x, (1, 0, 2))
y

array([[[1., 1., 1.]],

       [[1., 1., 1.]]])

In [22]:
y.shape

(2, 1, 3)

In [25]:
c = a.dot(b)
c

32

In [26]:
d = np.array([(1,2,3), (4,5,6)])
d

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
d = np.array(((1,2,3), (4,5,6)))
d

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
from __future__ import print_function

import pandas as pd
pd.__version__

'0.23.4'

In [34]:
from __future__ import print_function

import math

from IPython import display
from matplotlib import cm
from matplotlib import gridspec
from matplotlib import pyplot as plt
import numpy as np
import pandas as pd
from sklearn import metrics
import tensorflow as tf
from tensorflow.python.data import Dataset

tf.logging.set_verbosity(tf.logging.ERROR)
pd.options.display.max_rows = 10
pd.options.display.float_format = '{:.1f}'.format

In [35]:
california_housing_dataframe = pd.read_csv("https://download.mlcc.google.com/mledu-datasets/california_housing_train.csv", sep=",")

URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)>

In [ ]:
california_housing_dataframe.head()