In [ ]:
# 原始数据：user, item, favorate
# 形成 user 和 item 的 matrix
# 计算 user 的相似度；
# 输入：target user；k 最相近的 5 个user；最推荐的 p 个 items；
# 输出：对于 target_user 的相似度，从高到低排序，取前 k 个 user； 
# 取出 target_user 的 items，记为 A；再取出这 k 个 user 的产品，记为 B；计算 C = B - A，表示 target 可能感兴趣的 item；
# 对于 C 中的每一个 item，如果 第i个 user 有记录，把 target 和 i 的相似度作为权重，乘以 i对C 的数量，最后再累加，得到 item 的总数值 m；
# C 按 m 降序，取前面 p 个，输出；

In [63]:
import numpy as np
import pandas as pd
from sklearn.metrics.pairwise import pairwise_distances

# 读入u.data数据文件
header = ['user_id', 'item_id', 'rating', 'timestamp']
df = pd.read_csv('./ml-100k/u.data', sep = '\t', names = header)

# 查看用户和电影的数量
n_users = df.user_id.unique().shape[0]
n_items = df.item_id.unique().shape[0]
print('Number of users = {} | Number of movies = {}'.format(n_users, n_items))

data_matrix = np.zeros((n_users, n_items))
for line in df.itertuples():
    data_matrix[line[1]-1, line[2]-1] = line[3]
    

Number of users = 943 | Number of movies = 1682


In [64]:

row_similarity = 1 - pairwise_distances(data_matrix, metric="cosine")    

row_similarity[0:4, 0:4]

array([[1.        , 0.16693098, 0.04745954, 0.06435782],
       [0.16693098, 1.        , 0.11059132, 0.17812119],
       [0.04745954, 0.11059132, 1.        , 0.34415072],
       [0.06435782, 0.17812119, 0.34415072, 1.        ]])

In [66]:
df.loc[df["user_id"]==437]

user_id  item_id  rating  timestamp
16584      437      165       4  881002324
16714      437     1121       5  880140466
16756      437      708       4  881002026
16822      437     1404       2  881002263
16825      437      190       3  880140154
16889      437      419       5  880141961
16946      437       14       5  880140369
17145      437      655       4  881001945
17522      437     1262       3  881002091
17688      437      173       4  881001023
17749      437      755       3  880143450
17796      437       86       4  881001715
17822      437      665       2  880143695
17823      437      239       4  880141529
17960      437      197       5  880141962
18319      437      640       1  881002300
18404      437      584       3  880141243
18454      437      418       3  880141084
18808      437     1113       4  881002161
19030      437      451       5  880143115
19160      437      696       3  880142991
19398      437      652       4  881001983
19527      437     1153       5  880141962
19531      437      118       2  880142991
19548      437      499       5  880141962
20022      437      423       5  880141196
20110      437      727       3  881001576
20271      437      166       4  880140398
20328      437        5       2  880143663
20331      437      214       4  880141041
...        ...      ...     ...        ...
77832      437      153       5  881001888
77905      437      139       3  881001576
78412      437      182       2  880140432
79851      437     1267       4  880141528
80129      437      226       1  880142942
80134      437       15       4  881001946
80467      437       23       4  880140288
80602      437      156       2  880140627
80804      437      961       5  881002323
80935      437     1142       4  880141696
81004      437      117       1  881001121
82248      437      602       3  880140822
82293      437      476       4  880142177
82447      437      196       4  880140627
82743      437      100       4  880140051
85026      437        8       4  880140752
85712      437      249       5  880142027
85762      437      420       3  881002191
86406      437      152       4  880141129
87465      437      401       5  880143505
87727      437      129       1  880140433
89636      437      202       5  881001715
89656      437      215       3  880140325
90590      437      248       2  880141716
92244      437      558       3  880142365
92538      437      319       5  881001538
93518      437      210       3  881002191
98307      437      135       4  880140101
98564      437       66       3  880143167
99156      437      462       5  881002324

[263 rows x 4 columns]

In [41]:
c = a[2, :]
print(c)

[[10 11 12 13]]


In [43]:
test = np.array([[1, 2], [3, 4], [5, 6]])

In [44]:
print(test)

[[1 2]
 [3 4]
 [5 6]]


In [45]:
print(test[1, :])

[3 4]


In [73]:
import math

math.cos(math.pi/3)

0.5000000000000001

In [76]:
math.cos(65 / 180 * math.pi)

0.42261826174069944