In [1]:
# 特征值分解


# eigendecomposition
from numpy import array
from numpy.linalg import eig

# define matrix
A = array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(A)

# calculate eigendecomposition
values, vectors = eig(A)
print(values)
print(vectors)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [2]:
# 验证 

# confirm eigenvector
from numpy import array
from numpy.linalg import eig

# define matrix
A = array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# calculate eigendecomposition
values, vectors = eig(A)
# confirm first eigenvector
B = A.dot(vectors[:, 0])
print(B)

C = values[0] * vectors[:, 0]
print(C)

[ -3.73863537  -8.46653421 -13.19443305]
[ -3.73863537  -8.46653421 -13.19443305]


In [3]:
# 逆运算

# reconstruct matrix
from numpy import diag
from numpy import dot
from numpy.linalg import inv
from numpy import array
from numpy.linalg import eig

# define matrix
A = array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(A)

# calculate eigenvectors and eigenvalues
values, vectors = eig(A)

# create matrix from eigenvectors
Q = vectors
# create inverse of eigenvectors matrix
R = inv(Q)
# create diagonal matrix from eigenvalues
L = diag(values)

# reconstruct the original matrix
B = Q.dot(L).dot(R)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
