In [2]:
# LU 分解

from numpy import array
from scipy.linalg import lu

# define a square matrix
A = array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("input: ", A)

# LU decomposition
# P 是行顺序调整
P, L, U = lu(A)
print(P)
print(L)
print(U)

# reconstruct
B = P.dot(L).dot(U)
print("out: ", B)

C = L.dot(U)
print("out2: ", C)

input:  [[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[1.         0.         0.        ]
 [0.14285714 1.         0.        ]
 [0.57142857 0.5        1.        ]]
[[ 7.00000000e+00  8.00000000e+00  9.00000000e+00]
 [ 0.00000000e+00  8.57142857e-01  1.71428571e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.58603289e-16]]
out:  [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
out2:  [[7. 8. 9.]
 [1. 2. 3.]
 [4. 5. 6.]]


In [6]:
# QR 分解: Q 单位正交基；R 在这组基下的坐标

# QR decomposition
from numpy import array
from numpy.linalg import qr
# define a 3x2 matrix
A = array([[1, 2], [3, 4], [5, 6]])
print("A: ", A)
# QR decomposition，默认返回 ‘reduced’ dimensions that is more economical
Q, R = qr(A, 'complete')
print("Q: ",  Q)
print("R: ", R)
# reconstruct
B = Q.dot(R)
print("B: ", B)

# Q 列向量正交
print(Q[1])
print(Q[1].dot(Q[2]))

A:  [[1 2]
 [3 4]
 [5 6]]
Q:  [[-0.16903085  0.89708523  0.40824829]
 [-0.50709255  0.27602622 -0.81649658]
 [-0.84515425 -0.34503278  0.40824829]]
R:  [[-5.91607978 -7.43735744]
 [ 0.          0.82807867]
 [ 0.          0.        ]]
B:  [[1. 2.]
 [3. 4.]
 [5. 6.]]
[-0.50709255  0.27602622 -0.81649658]
0.0


In [7]:
# Cholesky Decomposition: 针对 正定矩阵，positive definite matrices

# A = L * LT； L:下三角矩阵

# Cholesky decomposition
from numpy import array
from numpy.linalg import cholesky
# define a 3x3 matrix
A = array([[2, 1, 1], [1, 2, 1], [1, 1, 2]])
print(A)
# Cholesky decomposition
L = cholesky(A)
print(L)
# reconstruct
B = L.dot(L.T)
print(B)

[[2 1 1]
 [1 2 1]
 [1 1 2]]
[[1.41421356 0.         0.        ]
 [0.70710678 1.22474487 0.        ]
 [0.70710678 0.40824829 1.15470054]]
[[2. 1. 1.]
 [1. 2. 1.]
 [1. 1. 2.]]
